### ISSUE TITLE
`faiss` issue on install

### ISSUE THREAD

**Issue by bkj** [DeepGraphLearning/graphvite#30]
When I try to follow the "install from source" directions in the README, I hit the following error:
```
software/graphvite/include/instance/visualization.cuh:25:36: fatal error: faiss/gpu/GpuIndexFlat.h: No such file or directory
```

Any idea how to solve?  I tried installing `faiss` in various different ways but wasn't able to get it running.

Thanks!
~ Ben

**Comment by KiddoZhu** [comment]
The recommended practice is to let GraphVite automatically compile faiss from source (if you have Internet access).

Otherwise, you can manually specify the path to faiss repo by `cmake .. -DFAISS_PATH=/path/to/faiss`. This requires faiss to be compiled in advance.

Actually you can skip faiss if you don't need the visualization application. You can comment out all faiss related lines in `CMakeLists.txt` and `visualization.cuh`. We may add a shortcut to such skip in the future.

**Comment by bkj** [comment]
OK thanks.  It seems like "let GraphVite automatically compile faiss from source" isn't working out-of-the-box per the error above -- is there some flag or path that needs to be set there?

**Comment by KiddoZhu** [comment]
The conda routine always compiles in that way. I think it should work.

Could you check the following steps?
- Whether faiss repo is present in `external/`
- What's the faiss path detected by cmake? You may use `cat build/CMakeCache.txt | grep FAISS`

**Comment by bkj** [comment]
- `faiss` appears to be present in external
- `cat build/CMakeCache.txt | grep FAISS` finds nothing

**Comment by KiddoZhu** [comment]
It seems good. I also checked `CMakeLists.txt` and didn't find any obvious bug.

Can you find these two files? They should present if faiss has been compiled automatically by graphvite.
- `build/faiss/include/faiss/gpu/GpuIndexFlat.h`
- `build/faiss/lib/libfaiss.so`

If they are present, can you add this line at the bottom of `CMakeLists.txt` and re-run `cmake ..`?
```message(STATUS ${PROJECT_BINARY_DIR})```

This is expected to output the full path of `build/`. As you may find, we have already added `${PROJECT_BINARY_DIR}/faiss/include` in `CMakeLists.txt`:104.
